const students = [{
    "userId": 1,
    "ethAddress": "Matthaeus",
    "facebookId": "Gourdon",
    "twitterHandle": "mgourdon0@barnesandnoble.com"
  }, {
    "userId": 2,
    "ethAddress": "George",
    "facebookId": "Westby",
    "twitterHandle": "gwestby1@abc.net.au"
  }, {
    "userId": 3,
    "ethAddress": "Joshua",
    "facebookId": "Thresh",
    "twitterHandle": "jthresh2@paginegialle.it"
  }, {
    "userId": 4,
    "ethAddress": "Krishnah",
    "facebookId": "Foskett",
    "twitterHandle": "kfoskett3@reddit.com"
  }, {
    "userId": 5,
    "ethAddress": "Kyla",
    "facebookId": "Buxton",
    "twitterHandle": "kbuxton4@fema.gov"
  }, {
    "userId": 6,
    "ethAddress": "Sybilla",
    "facebookId": "Swoffer",
    "twitterHandle": "sswoffer5@mac.com"
  }, {
    "userId": 7,
    "ethAddress": "Alex",
    "facebookId": "Clyant",
    "twitterHandle": "aclyant6@bigcartel.com"
  }, {
    "userId": 8,
    "ethAddress": "Winthrop",
    "facebookId": "Bonefant",
    "twitterHandle": "wbonefant7@dell.com"
  }, {
    "userId": 9,
    "ethAddress": "Octavius",
    "facebookId": "Zorzoni",
    "twitterHandle": "ozorzoni8@dot.gov"
  }, {
    "userId": 10,
    "ethAddress": "Ancell",
    "facebookId": "Ricca",
    "twitterHandle": "aricca9@princeton.edu"
  }]
  
module.exports = students;
